"""
vector_search/vector_store.py

Milestone 4 — Embeddings & Semantic Search.

Wraps a local, persistent ChromaDB collection called "products". Owns:
opening/creating the collection, upserting product vectors + metadata,
and running similarity queries. No SBERT calls happen here — embeddings
are always generated by embeddings.embedding_generator and passed in.
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional

import chromadb

logger = logging.getLogger(__name__)

COLLECTION_NAME = "products"


def get_chroma_client(persist_dir: Path) -> chromadb.PersistentClient:
    """Type: Rule-based. Open (or create) the on-disk ChromaDB store."""
    persist_dir.mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=str(persist_dir))


def get_products_collection(client: chromadb.PersistentClient):
    """
    Type: Rule-based. Get-or-create the 'products' collection.

    Cosine distance is used since SBERT embeddings are compared by angle,
    not magnitude. embedding_function=None disables Chroma's own default
    embedder — we always supply embeddings ourselves, so this collection
    should never try to embed anything on its own.
    """
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
        embedding_function=None,
    )


# ChromaDB's client enforces a max items-per-call limit on upsert/add
# (observed: 5461 on this machine's Chroma version -- the exact number
# is derived from the underlying batch executor, not a constant Chroma
# publishes, so we stay comfortably under it rather than hardcode their
# ceiling). Batching here means every caller of upsert_products is
# protected, not just build_vector_index.py.
MAX_UPSERT_BATCH_SIZE = 5000


def upsert_products(
    collection,
    product_ids: List[str],
    embeddings,
    metadatas: List[Dict],
    documents: Optional[List[str]] = None,
) -> None:
    """
    Type: Rule-based.
    Upsert (not blind insert) product vectors — re-running the batch
    script updates existing rows in place instead of duplicating them.
    `documents` (the embedding text) is stored too so debugging/tests
    can see exactly what was embedded.

    Chunks internally into batches of MAX_UPSERT_BATCH_SIZE, since
    Chroma rejects a single upsert() call above its internal max batch
    size (hit in practice once the catalog crossed ~6000 products).
    """
    ids = [str(pid) for pid in product_ids]
    embeddings_list = embeddings.tolist() if hasattr(embeddings, "tolist") else embeddings

    total = len(ids)
    for start in range(0, total, MAX_UPSERT_BATCH_SIZE):
        end = start + MAX_UPSERT_BATCH_SIZE
        collection.upsert(
            ids=ids[start:end],
            embeddings=embeddings_list[start:end],
            metadatas=metadatas[start:end],
            documents=documents[start:end] if documents is not None else None,
        )
        logger.info(f"  upserted batch [{start}:{min(end, total)}] ({min(end, total) - start} products)")

    logger.info(f"Upserted {total} products into '{collection.name}' in {(total + MAX_UPSERT_BATCH_SIZE - 1) // MAX_UPSERT_BATCH_SIZE} batch(es)")


def query_similar(collection, query_embedding, top_k: int = 5) -> List[Dict]:
    """
    Type: Rule-based.
    Nearest-neighbour search against a single query embedding. Returns a
    list of dicts with product_id, metadata, embedding text, and a
    similarity score the caller can see (never hidden).

    ChromaDB's cosine space returns distance = 1 - cosine_similarity, so
    similarity = 1 - distance. Verified against manual cosine calculations
    before shipping this.
    """
    results = collection.query(
        query_embeddings=[query_embedding.tolist() if hasattr(query_embedding, "tolist") else query_embedding],
        n_results=top_k,
    )

    output = []
    ids = results["ids"][0]
    distances = results["distances"][0]
    metadatas = results["metadatas"][0]
    documents = results["documents"][0]

    for i in range(len(ids)):
        similarity = 1 - distances[i]
        output.append({
            "product_id": ids[i],
            "similarity": round(float(similarity), 4),
            "metadata": metadatas[i],
            "embedding_text": documents[i],
        })
    return output
