"""
vector_search/vector_store.py

Milestone 4 — Embeddings & Semantic Search.

Wraps a local, persistent ChromaDB collection called "products". Owns:
opening/creating the collection, upserting product vectors + metadata,
and running similarity queries. No SBERT calls happen here — embeddings
are always generated by embeddings.embedding_generator and passed in.
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional

import chromadb

logger = logging.getLogger(__name__)

COLLECTION_NAME = "products"


def get_chroma_client(persist_dir: Path) -> chromadb.PersistentClient:
    """Type: Rule-based. Open (or create) the on-disk ChromaDB store."""
    persist_dir.mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=str(persist_dir))


def get_products_collection(client: chromadb.PersistentClient):
    """
    Type: Rule-based. Get-or-create the 'products' collection.

    Cosine distance is used since SBERT embeddings are compared by angle,
    not magnitude. embedding_function=None disables Chroma's own default
    embedder — we always supply embeddings ourselves, so this collection
    should never try to embed anything on its own.
    """
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
        embedding_function=None,
    )


def upsert_products(
    collection,
    product_ids: List[str],
    embeddings,
    metadatas: List[Dict],
    documents: Optional[List[str]] = None,
) -> None:
    """
    Type: Rule-based.
    Upsert (not blind insert) product vectors — re-running the batch
    script updates existing rows in place instead of duplicating them.
    `documents` (the embedding text) is stored too so debugging/tests
    can see exactly what was embedded.
    """
    collection.upsert(
        ids=[str(pid) for pid in product_ids],
        embeddings=embeddings.tolist() if hasattr(embeddings, "tolist") else embeddings,
        metadatas=metadatas,
        documents=documents,
    )
    logger.info(f"Upserted {len(product_ids)} products into '{collection.name}'")


def query_similar(collection, query_embedding, top_k: int = 5) -> List[Dict]:
    """
    Type: Rule-based.
    Nearest-neighbour search against a single query embedding. Returns a
    list of dicts with product_id, metadata, embedding text, and a
    similarity score the caller can see (never hidden).

    ChromaDB's cosine space returns distance = 1 - cosine_similarity, so
    similarity = 1 - distance. Verified against manual cosine calculations
    before shipping this.
    """
    results = collection.query(
        query_embeddings=[query_embedding.tolist() if hasattr(query_embedding, "tolist") else query_embedding],
        n_results=top_k,
    )

    output = []
    ids = results["ids"][0]
    distances = results["distances"][0]
    metadatas = results["metadatas"][0]
    documents = results["documents"][0]

    for i in range(len(ids)):
        similarity = 1 - distances[i]
        output.append({
            "product_id": ids[i],
            "similarity": round(float(similarity), 4),
            "metadata": metadatas[i],
            "embedding_text": documents[i],
        })
    return output
