"""
config/settings.py

Central place for filesystem paths and pipeline constants.
Everything is relative to the project root so the pipeline works
regardless of which machine or working directory it's run from.

Rule-based module: no AI/ML here, just configuration.
"""

from pathlib import Path

# Project root = two levels up from this file (config/settings.py -> project root)
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# --- Data directories ---
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EDA_DIR = DATA_DIR / "eda"

# --- Raw (pre-cleaning) file paths ---
RAW_PRODUCTS_PATH = RAW_DATA_DIR / "products.csv"
RAW_REVIEWS_PATH = RAW_DATA_DIR / "reviews.csv"
RAW_USERS_PATH = RAW_DATA_DIR / "users.csv"
RAW_INTERACTIONS_PATH = RAW_DATA_DIR / "interactions.csv"

# --- Processed (post-cleaning) file paths ---
CLEAN_PRODUCTS_PATH = PROCESSED_DATA_DIR / "products_clean.csv"
CLEAN_REVIEWS_PATH = PROCESSED_DATA_DIR / "reviews_clean.csv"
CLEAN_USERS_PATH = PROCESSED_DATA_DIR / "users_clean.csv"
CLEAN_INTERACTIONS_PATH = PROCESSED_DATA_DIR / "interactions_clean.csv"

# --- Reports ---
QUALITY_REPORT_PATH = PROCESSED_DATA_DIR / "data_quality_report.json"
VALIDATION_LOG_PATH = PROCESSED_DATA_DIR / "validation_report.json"

# --- Dataset generation constants (synthetic data, clearly labeled) ---
DATA_SOURCE_LABEL = "synthetic_v1"  # written into every generated row's `source` column
RANDOM_SEED = 42
NUM_PRODUCTS = 400
NUM_USERS = 120
MIN_REVIEWS_PER_PRODUCT = 0
MAX_REVIEWS_PER_PRODUCT = 12
MIN_INTERACTIONS_PER_USER = 3
MAX_INTERACTIONS_PER_USER = 25

# --- Validation ranges (used by backend/services/validation.py) ---
VALID_RATING_RANGE = (0.0, 5.0)
VALID_PERCENTAGE_RANGE = (0.0, 100.0)
VALID_SCORE_RANGE = (0.0, 1.0)  # for recyclability_score, repairability_score

# =============================================================================
# Milestone 3 — Sustainability Intelligence Engine
# =============================================================================

# --- Module + model directories ---
SUSTAINABILITY_DIR = PROJECT_ROOT / "sustainability"
MODELS_DIR = PROJECT_ROOT / "models"

# --- Output of the batch scoring script ---
SCORED_PRODUCTS_PATH = PROCESSED_DATA_DIR / "products_scored.csv"

# --- Trained ML artifact (gitignored, regenerated by scripts/train_sustainability_model.py) ---
SUSTAINABILITY_ML_MODEL_PATH = MODELS_DIR / "sustainability_ml_model.joblib"

# --- Rule-based scorer: component weights (must sum to 1.0) ---
SUSTAINABILITY_COMPONENT_WEIGHTS = {
    "carbon_footprint_kg": 0.20,
    "recycled_material_percentage": 0.15,
    "eco_certification": 0.15,
    "water_usage_liters": 0.15,
    "recyclability_score": 0.10,
    "repairability_score": 0.10,
    "organic_material_percentage": 0.10,
    "product_lifetime_years": 0.05,
}

# --- Rule-based scorer: normalization bounds (fixed, not data-derived) ---
CARBON_FOOTPRINT_BOUNDS = (0.0, 10.0)   # kg CO2e per unit; 0 = best, 10 = worst
WATER_USAGE_BOUNDS = (0.0, 5000.0)      # liters per unit; 0 = best, 5000 = worst
PRODUCT_LIFETIME_BOUNDS = (0.0, 8.0)    # years; 0 = worst, 8 = best (soft cap)

# --- Rule-based scorer: eco_certification quality mapping ---
ECO_CERTIFICATION_SCORES = {
    "No Certification": 0.0,
    "OEKO-TEX": 0.55,
    "Fair Trade": 0.60,
    "Global Recycled Standard": 0.75,
    "GOTS": 0.90,
}

# --- Final blended score: sustainability_score = blend of rule-based + ML ---
ML_BLEND_WEIGHT = 0.4  # weight given to the ML model's score; rule-based gets (1 - this)

# --- ML proxy-target generation (see sustainability/ml_scorer.py docstring) ---
ML_TRAINING_RANDOM_SEED = 42
ML_PROXY_NOISE_STD = 0.05  # Gaussian noise std added to the synthetic proxy label

# --- Milestone 4: Embeddings & Semantic Search ---
PRODUCTS_SCORED_PATH = PROCESSED_DATA_DIR / "products_scored.csv"
CHROMA_PERSIST_DIR = PROJECT_ROOT / "data" / "chroma_store"
SEMANTIC_SEARCH_TOP_K_DEFAULT = 5

# ==================== MILESTONE 5: RECOMMENDATION BLENDING & RANKING ====================
import os as _os_m5

# Assumes PROCESSED_DATA_DIR already exists from earlier milestones (data/processed/).
# If your constant is named differently, change just this one line.
MILESTONE5_INTERACTIONS_CLEAN_PATH = _os_m5.path.join(PROCESSED_DATA_DIR, "interactions_clean.csv")

RECOMMENDATION_CANDIDATE_POOL_SIZE = 50   # semantic candidates pulled before blending
CONTENT_MIN_SIMILARITY_THRESHOLD = 0.20   # below this best-match score, flag out_of_domain_query

HYBRID_WEIGHTS_DEFAULT = {
    "content": 0.5,
    "collaborative": 0.3,
    "sustainability": 0.2,
}

# ==================== MILESTONE 6: REVIEW SENTIMENT INTELLIGENCE ====================
from pathlib import Path as _M6Path

SENTIMENT_MODEL_NAME = "distilbert-base-uncased-finetuned-sst-2-english"
SENTIMENT_MODEL_CACHE_DIR = _M6Path(__file__).resolve().parent.parent / "models" / "sentiment_model_cache"
REVIEWS_CLEAN_PATH = "data/processed/reviews_clean.csv"
PRODUCT_SENTIMENT_OUTPUT_PATH = "data/processed/product_sentiment.csv"

# ==================== MILESTONE 7: INTENT EXTRACTION ====================
CATALOG_CATEGORIES = ["Shoes", "Bags", "T-Shirts", "Jeans", "Jackets", "Shirts", "Dresses"]

# ==================== MILESTONE 8: WIRING INTENT INTO SEARCH & BLENDING ====================
# Fraction of weight shifted from content/collaborative into sustainability
# when sustainability_emphasis=True is detected by intent extraction.
# Applied AFTER cold-start renormalization, proportionally across whichever
# of content/collaborative are actually present at that point.
SUSTAINABILITY_TILT_AMOUNT = 0.15

# ---- Milestone 9: FastAPI settings ----
API_HOST = "127.0.0.1"
API_PORT = 8000
API_CORS_ORIGINS = ["*"]  # DEV ONLY -- restrict to real origins before deployment
API_MAX_TOP_K = 50

# ---- Milestone 10: Frontend settings ----
API_BASE_URL = "http://127.0.0.1:8000"
